language: csharp
install: true
mono: none
dotnet: 2.1.502
sudo: required
git:
  depth: false
branches:
  only:
    - master
script:
  - ./build.sh --target=Deploy-CI
env:
  - DeployTo="https://linker-demo.scm.azurewebsites.net/api/zipdeploy"
